Repository micronaut-projects/micronaut-aws, pull requests merged in 2020-10, with the labels that each got.

#598 Upgrade AWS SDK to 1.11.880
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#604 Upgrade AWS SDK to 2.15.7
  aws-sdk-v2/build.gradle
Labels: type: dependency-upgrade

#614 [aws] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#615 [aws] Update common files for branch 2.1.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#607 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#626 feat: adds mdc keys for context entries and xray
  function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestHandler.java
  function-aws/src/test/groovy/io/micronaut/function/aws/MappingDiagnosticContextSetterSpec.groovy
  function-aws/src/test/groovy/io/micronaut/function/aws/SquareHandlerSpec.groovy
  src/main/docs/guide/lambda/mdc.adoc
  src/main/docs/guide/toc.yml
Labels: type: improvement

#627 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#644 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade
