Repository micronaut-projects/micronaut-aws, pull requests merged in 2020-08, with the labels that each got.

#438 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#439 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#441 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#442 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-aws-custom-runtime/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#448 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#456 [aws] Update common files for branch 1.4.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#455 [aws] Update common files for branch master
  README.md
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#458 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#460 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#464 [aws] Update common files for branch 1.4.x
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: relates-to: build

#463 [aws] Update common files for branch master
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: relates-to: build

#466 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#468 [aws] Update common files for branch master
  .github/workflows/release-notes.yml
Labels: relates-to: build

#469 [aws] Update common files for branch 1.4.x
  .github/workflows/release-notes.yml
Labels: relates-to: build

#470 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-client-aws/build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#473 Update Gradle to 6.6.1
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#472 Bump up gradle to 6.6.1
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#471 doc: Improve lamda documentation
  src/main/docs/guide/lambda.adoc
  src/main/docs/guide/lambda/apiProxy.adoc
  src/main/docs/guide/lambda/applicationtyperuntimedependencies.adoc
  src/main/docs/guide/lambda/applicationtypesforawslambda.adoc
  src/main/docs/guide/lambda/awslambdaconsiderations.adoc
  src/main/docs/guide/lambda/awslambdaruntimes.adoc
  src/main/docs/guide/lambda/coldstartups.adoc
  src/main/docs/guide/lambda/customRuntimes.adoc
  src/main/docs/guide/lambda/lambdaTutorials.adoc
  src/main/docs/guide/lambda/lambdatriggers.adoc
  src/main/docs/guide/lambda/requestHandlers.adoc
  src/main/docs/guide/lambdaCustomRuntimes/customRuntimeApiGateway.adoc
  src/main/docs/guide/lambdaCustomRuntimes/customRuntimeDeploy.adoc
  src/main/docs/guide/lambdaCustomRuntimes/customRuntimeGraal.adoc
  src/main/docs/guide/lambdaCustomRuntimes/customRuntimeHandler.adoc
  src/main/docs/guide/toc.yml
  src/main/docs/resources/img/aws-lambda-runtime-custom.png
  src/main/docs/resources/img/aws-lambda-runtime-java11.png
Labels: type: docs

#476 Revert minor versions
  aws-alexa-httpserver/build.gradle
  aws-alexa/build.gradle
  aws-sdk-v2/build.gradle
  function-aws-alexa/build.gradle
  function-aws-custom-runtime/build.gradle
Labels: relates-to: build

#478 ci: githubCoreBranch to 2.0.x
  gradle.properties
Labels: relates-to: build

#477 Update releases.adoc
  src/main/docs/guide/releases.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs
