Repository micronaut-projects/micronaut-aws, pull requests merged in 2020-12, with the labels that each got.

#764 Github actions, MANTAINING.md, gradle 6.7.1
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  MAINTAINING.md
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#725 Github actions, gradle 6.7.1
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/release-notes.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#778 Fix request parameter gathering in AWS proxy adapter
  function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/DefaultServletToAwsProxyRequestAdapter.java
  function-aws-api-proxy-test/src/test/groovy/io/micronaut/function/aws/proxy/test/AwsApiProxyTestServerSpec.groovy
Labels: type: bug

#726 build: update asciidoc-config, micronaut-security and AWS to patch versions
  aws-alexa-httpserver/build.gradle
  aws-alexa/build.gradle
  aws-common/build.gradle
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  build.gradle
  function-aws-alexa/build.gradle
  function-aws-api-proxy-test/build.gradle
  function-aws-api-proxy/build.gradle
  function-aws-custom-runtime/build.gradle
  function-aws/build.gradle
  function-client-aws/build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#780 build: bump up aws sdk to 2.15.40
  aws-sdk-v2/build.gradle
Labels: type: dependency-upgrade

#779 build: bump up aws-java-sdk to 1.11.913
  aws-route53/build.gradle
Labels: type: dependency-upgrade

#782 ci: set github core branch to 2.3.x
  gradle.properties
Labels: relates-to: build

#781 build: bump up project version to 2.3.0-SNAPSHOT
  gradle.properties
Labels: relates-to: build

#810 feat: add SsmClient bean
  aws-sdk-v2/build.gradle
  aws-sdk-v2/src/main/java/io/micronaut/aws/sdk/v2/service/ssm/SsmClientFactory.java
  aws-sdk-v2/src/main/java/io/micronaut/aws/sdk/v2/service/ssm/package-info.java
  aws-sdk-v2/src/test/groovy/io/micronaut/aws/sdk/v2/service/SsmClientSpec.groovy
  src/main/docs/guide/sdkv2/ssm.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement

#783 build: aws sdk to 2.15.45 and aws-java-sdk to 1.11.918
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-aws-api-proxy-test/build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#816 ci: don't publish test reports
  .github/workflows/gradle.yml
Labels: relates-to: build
