Repository micronaut-projects/micronaut-aws, pull requests merged in 2020-09, with the labels that each got.

#480 ci: set github core branch to 2.1.x
  gradle.properties
Labels: relates-to: build

#479 Fix asciidoc table
  src/main/docs/guide/lambda/requestHandlers.adoc
Labels: type: docs

#481 build: Set version to 2.1.0.BUILD-SNAPSHOT
  gradle.properties
Labels: relates-to: build

#484 build: bump up aws sdk to 2.14.7
  aws-sdk-v2/build.gradle
Labels: relates-to: build

#485 build: bump up aws-lambda-java-events 3.2.0
  function-aws-custom-runtime/build.gradle
Labels: relates-to: build

#486 Fix asciidoctor table
  src/main/docs/guide/lambda/requestHandlers.adoc
Labels: type: docs

#487 Dependency upgrades
  aws-alexa-httpserver/build.gradle
  aws-alexa/build.gradle
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-aws-alexa/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#494 Dependency upgrades
  aws-alexa-httpserver/build.gradle
  aws-alexa/build.gradle
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-aws-alexa/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#498 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#500 Upgrade ASK SDK from 2.33.0 to 2.34.0 and aws-java-sdk from 1.11.857 to 1.11.858
  aws-alexa-httpserver/build.gradle
  aws-alexa/build.gradle
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-aws-alexa/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#499 refactor: Split proxy-test into beans
  function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/AwsApiProxyTestServer.java
  function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/ContextProvider.java
  function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/DefaultServletToAwsProxyRequestAdapter.java
  function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/DefaultServletToAwsProxyResponseAdapter.java
  function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/MockContextProvider.java
  function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/ServerPort.java
  function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/ServletToAwsProxyRequestAdapter.java
  function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/ServletToAwsProxyResponseAdapter.java
Labels: type: improvement

#501 Extra add converter method
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaHandler.java
Labels: type: improvement

#504 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#505 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#509 [aws] Update common files for branch 2.0.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#508 [aws] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#507 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade
