Repository micronaut-projects/micronaut-aws, pull requests merged in 2021-07, with the labels that each got.

#1093 ci: Github actions and Gradle to 7.1.1
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#1115 Update coldstartups.adoc
  src/main/docs/guide/lambda/coldstartups.adoc
Labels: type: docs

#1122 deprecated: ctx.builder() instead of build()
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/BodySpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ConsumesSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/CookiesSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ErrorHandlerSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/FiltersSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/FluxSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/MicronautLambdaHandlerSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ObjectMapperListenerSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ObjectMapperSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ParametersSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ResponseStatusSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/VersionSpec.groovy
  function-aws-api-proxy/src/test/java/io/micronaut/function/aws/proxy/HelloWorldMicronautTest.java
  function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntime.java
Labels: type: improvement

#1126 test: delete RefreshInterceptorWorkAround
  function-aws-alexa/src/test/groovy/io/micronaut/function/aws/alexa/RefreshInterceptorWorkAround.groovy
Labels: type: improvement

#1127 doc: breaks by major version
  src/main/docs/guide/mnawstwo.adoc
  src/main/docs/guide/mnawstwo/mnawstwoBreaks.adoc
  src/main/docs/guide/mnawstwo/mnawstwoWhatsNew.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#1134 BREAKING CHANGE: remove module route53
  aws-parameter-store/build.gradle
  aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterStoreConfigClient.java
  aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterStoreConfiguration.java
  aws-route53/build.gradle
  aws-route53/src/main/java/io/micronaut/discovery/aws/route53/AWSServiceDiscoveryClientConfiguration.java
  aws-route53/src/main/java/io/micronaut/discovery/aws/route53/AWSServiceDiscoveryClientResolver.java
  aws-route53/src/main/java/io/micronaut/discovery/aws/route53/AWSServiceDiscoveryResolver.java
  aws-route53/src/main/java/io/micronaut/discovery/aws/route53/Route53AutoRegistrationConfiguration.java
  aws-route53/src/main/java/io/micronaut/discovery/aws/route53/Route53ClientDiscoveryConfiguration.java
  aws-route53/src/main/java/io/micronaut/discovery/aws/route53/Route53DiscoveryConfiguration.java
  aws-route53/src/main/java/io/micronaut/discovery/aws/route53/client/Route53AutoNamingClient.java
  aws-route53/src/main/java/io/micronaut/discovery/aws/route53/client/package-info.java
  aws-route53/src/main/java/io/micronaut/discovery/aws/route53/package-info.java
  aws-route53/src/main/java/io/micronaut/discovery/aws/route53/registration/EC2ServiceInstance.java
  aws-route53/src/main/java/io/micronaut/discovery/aws/route53/registration/Route53AutoNamingRegistrationClient.java
  aws-route53/src/main/java/io/micronaut/discovery/aws/route53/registration/ServiceRegistrationStatusTask.java
  aws-route53/src/main/java/io/micronaut/discovery/aws/route53/registration/package-info.java
  aws-route53/src/test/groovy/io/micronaut/discovery/aws/route53/MockAWSServiceDiscoveryAsync.groovy
  aws-route53/src/test/groovy/io/micronaut/discovery/aws/route53/Route53AutoNamingClientUnitSpec.groovy
  aws-service-discovery/src/main/java/io/micronaut/discovery/aws/servicediscovery/AwsServiceDiscoveryClientConfiguration.java
  settings.gradle
  src/main/docs/guide/mnawsthree.adoc
  src/main/docs/guide/mnawsthree/mnawsthreeBreaks.adoc
  src/main/docs/guide/toc.yml
Labels: type: breaking

#1136 BREAKING CHANGE: remove @IntentHandler (#1128)
  aws-alexa/src/main/java/io/micronaut/aws/alexa/annotation/IntentHandler.java
  aws-alexa/src/main/java/io/micronaut/aws/alexa/annotation/package-info.java
  aws-alexa/src/main/java/io/micronaut/aws/alexa/handlers/AnnotatedRequestHandler.java
  aws-alexa/src/main/java/io/micronaut/aws/alexa/handlers/package-info.java
  function-aws-alexa/src/test/groovy/io/micronaut/function/aws/alexa/AlexaFunctionSpec.groovy
  function-aws-alexa/src/test/java/io/micronaut/function/aws/alexa/TestAlexaApplicationHandler.java
  src/main/docs/guide/mnawsthree/mnawsthreeBreaks.adoc
Labels: type: breaking

#1137 ci: update graalvm to 21.2.0
  .github/workflows/graalvm.yml
Labels: relates-to: build

#1139 New issue templates
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/new_feature.yaml
  .github/ISSUE_TEMPLATE/other.yaml
Labels: relates-to: build

#1141 bump up aws-serverless-java-container-core to 1.6.0
  function-aws-api-proxy/build.gradle
  gradle.properties
Labels: type: dependency-upgrade
