Repository micronaut-projects/micronaut-aws, pull requests merged in 2021-08, with the labels that each got.

#1142 Fix broken links
  src/main/docs/guide/distributedconfiguration.adoc
  src/main/docs/guide/introduction.adoc
  src/main/docs/guide/lambda/lambdaTesting.adoc
  src/main/docs/guide/lambda/lambdaTutorials.adoc
  src/main/docs/guide/mnawsthree/mnawsthreeBreaks.adoc
  src/main/docs/guide/mnawstwo/mnawstwoBreaks.adoc
  src/main/docs/guide/mnawstwo/mnawstwoWhatsNew.adoc
  src/main/docs/guide/sdkv1/awsCredentialsProvider.adoc
Labels: type: docs

#1144 doc: Object Mapper Configuration
  src/main/docs/guide/lambda/objectmapperconfiguration.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#1146 Use JDK16 on CI
  .github/workflows/gradle.yml
Labels: relates-to: build

#1148 [aws] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#1151 doc: MicronautRequestStreamHandler and @FunctionBean
  build.gradle
  settings.gradle
  src/main/docs/guide/lambda/lambdaStreamHandler.adoc
  src/main/docs/guide/toc.yml
  test-suite-groovy/build.gradle
  test-suite-groovy/src/test/groovy/io/micronaut/docs/function/aws/EventLogger.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/function/aws/Handler.groovy
  test-suite-groovy/src/test/resources/logback.xml
  test-suite-kotlin/build.gradle
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/function/aws/EventLogger.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/function/aws/Handler.kt
  test-suite-kotlin/src/test/resources/logback.xml
  test-suite/build.gradle
  test-suite/src/test/groovy/io/micronaut/docs/function/aws/ContextFunctionNameSpec.groovy
  test-suite/src/test/groovy/io/micronaut/docs/function/aws/FactoryFunctionBeanSpec.groovy
  test-suite/src/test/groovy/io/micronaut/docs/function/aws/MicronautFunctionNameSpec.groovy
  test-suite/src/test/groovy/io/micronaut/docs/function/aws/MicronautRequestStreamHandlerOverrideResolveFunctionNameSpec.groovy
  test-suite/src/test/java/io/micronaut/docs/function/aws/CapitalizeFunction.java
  test-suite/src/test/java/io/micronaut/docs/function/aws/EventLogger.java
  test-suite/src/test/java/io/micronaut/docs/function/aws/FunctionsFactory.java
  test-suite/src/test/java/io/micronaut/docs/function/aws/Handler.java
  test-suite/src/test/java/io/micronaut/docs/function/aws/LowerCaseFunction.java
  test-suite/src/test/java/io/micronaut/docs/function/aws/UpperCaseFunction.java
  test-suite/src/test/resources/logback.xml
Labels: type: docs

#1154 test: AWSInvokeRequestDefinition.name
  function-client-aws/src/test/groovy/io/micronaut/function/client/aws/AwsLambdaInvokeSpec.groovy
Labels: type: improvement

#1155 fix: resolve AWSInvokeRequestDefinition name
  function-client-aws/src/main/java/io/micronaut/function/client/aws/AWSInvokeRequestDefinition.java
  function-client-aws/src/test/groovy/io/micronaut/function/client/aws/AwsLambdaInvokeSpec.groovy
Labels: type: bug

#1152 BREAKING CHANGE: micronaut.function.name precedence
  function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestStreamHandler.java
  src/main/docs/guide/lambda/lambdaStreamHandler.adoc
  src/main/docs/guide/mnawsthree/mnawsthreeBreaks.adoc
  test-suite/src/test/groovy/io/micronaut/docs/function/aws/ContextFunctionNameSpec.groovy
  test-suite/src/test/groovy/io/micronaut/docs/function/aws/MicronautFunctionNameSpec.groovy
Labels: type: breaking

#1157 doc: Document Lambda invocation via @FunctionClient
  src/main/docs/guide/lambda/lambdafunctionclient.adoc
  src/main/docs/guide/toc.yml
  test-suite-groovy/build.gradle
  test-suite-groovy/src/test/groovy/io/micronaut/docs/function/client/aws/AnalyticsClientSpec.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/function/client/aws/atnamed/AnalyticsClient.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/docs/function/client/aws/methodnamed/AnalyticsClient.groovy
  test-suite-groovy/src/test/resources/application.yml
  test-suite-kotlin/build.gradle
  test-suite-kotlin/src/test/groovy/io/micronaut/docs/function/client/aws/AnalyticsClientSpec.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/function/client/aws/atnamed/AnalyticsClient.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/function/client/aws/methodnamed/AnalyticsClient.kt
  test-suite-kotlin/src/test/resources/application.yml
  test-suite/build.gradle
  test-suite/src/test/groovy/io/micronaut/docs/function/aws/AnalyticsClientSpec.groovy
  test-suite/src/test/java/io/micronaut/docs/function/client/aws/atnamed/AnalyticsClient.java
  test-suite/src/test/java/io/micronaut/docs/function/client/aws/methodnamed/AnalyticsClient.java
  test-suite/src/test/resources/application.yml
Labels: type: docs
