Repository micronaut-projects/micronaut-aws, pull requests merged in 2021-03, with the labels that each got.

#883 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  build.gradle
  function-client-aws/build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#937 [aws] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#985 build: bump up micronaut security to 2.3.1
  gradle.properties
Labels: relates-to: build

#987 remove githubBranch
  gradle.properties
Labels: relates-to: build

#988 build: set GitHub core branch to 2.5.x
  gradle.properties
Labels: relates-to: build

#989 build: setup project version to 2.5.0-SNAPSHOT
  gradle.properties
Labels: relates-to: build

#992 delete example projects
  build.gradle
  examples/aws-parameter-store-example/README.md
  examples/aws-parameter-store-example/build.gradle
  examples/aws-parameter-store-example/gradle.properties
  examples/aws-parameter-store-example/src/main/java/com/example/Application.java
  examples/aws-parameter-store-example/src/main/java/com/example/Owner.java
  examples/aws-parameter-store-example/src/main/java/com/example/OwnerConfiguration.java
  examples/aws-parameter-store-example/src/main/java/com/example/OwnerController.java
  examples/aws-parameter-store-example/src/main/resources/application.yml
  examples/aws-parameter-store-example/src/main/resources/bootstrap.yml
  examples/aws-parameter-store-example/src/main/resources/logback.xml
  examples/aws-parameter-store-example/src/test/groovy/com/example/DemoSpec.groovy
  examples/aws-parameter-store-example/src/test/groovy/com/example/OwnerConfigurationTest.groovy
  settings.gradle
Labels: relates-to: build

#993 doc: delete broken section about `@IntentHandler`
  src/main/docs/guide/alexa/intentHandler.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#994 fix: remove unused import
  aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterStoreConfigClient.java
Labels: type: improvement

#996 build: root includes ann processor mn-inject-java
  aws-alexa-httpserver/build.gradle
  aws-alexa/build.gradle
  aws-common/build.gradle
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  function-aws-alexa/build.gradle
  function-aws-api-proxy-test/build.gradle
  function-aws-api-proxy/build.gradle
  function-aws-custom-runtime/build.gradle
  function-aws-test/build.gradle
  function-aws/build.gradle
  function-client-aws/build.gradle
Labels: relates-to: build

#995 build: root applies asciidoc-config to every subproject
  aws-alexa-httpserver/build.gradle
  aws-alexa/build.gradle
  aws-common/build.gradle
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  build.gradle
  function-aws-alexa/build.gradle
  function-aws-api-proxy/build.gradle
  function-aws-custom-runtime/build.gradle
  function-aws/build.gradle
  function-client-aws/build.gradle
Labels: relates-to: build

#997 build: root already adds ann micronaut-graal
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  function-aws-api-proxy/build.gradle
Labels: relates-to: build, relates-to: graal

#963 Add bom
  aws-bom/build.gradle
  aws-common/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  build.gradle
  function-aws-alexa/build.gradle
  function-aws-api-proxy-test/build.gradle
  function-aws-api-proxy/build.gradle
  function-aws-custom-runtime/build.gradle
  function-aws-test/build.gradle
  function-client-aws/build.gradle
  gradle.properties
  settings.gradle
Labels: relates-to: build

#998 Dependency upgrades
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
Labels: type: dependency-upgrade

#999 [aws] Update common files for branch master
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#1011 doc: it should "skills-id:" with :
  src/main/docs/guide/alexa.adoc
Labels: type: docs

#1010 javadoc: add javadoc
  function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntime.java
Labels: type: docs

#1015 doc: change order of alexa sections
  src/main/docs/guide/toc.yml
Labels: type: docs

#1012 annotate override method return type with @NonNull
  aws-alexa/src/main/java/io/micronaut/aws/alexa/builders/StandardSkillBuilderProvider.java
Labels: type: improvement

#1016 doc: split alexa documentation in sections
  aws-alexa-httpserver/build.gradle
  aws-alexa/build.gradle
  function-aws-alexa/build.gradle
  gradle.properties
  src/main/docs/guide/alexa.adoc
  src/main/docs/guide/alexa/alexahandlers.adoc
  src/main/docs/guide/alexa/alexaskillconfiguration.adoc
  src/main/docs/guide/alexa/skillbuilderprovider.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs
