Repository micronaut-projects/micronaut-aws, pull requests merged in 2021-05, with the labels that each got.

#1050 refactor: use micronaut nullability annotations
  aws-alexa-httpserver/src/main/java/io/micronaut/aws/alexa/httpserver/conf/AlexaControllerConfigurationProperties.java
  aws-alexa-httpserver/src/main/java/io/micronaut/aws/alexa/httpserver/services/DefaultRequestEnvelopeService.java
  aws-alexa-httpserver/src/main/java/io/micronaut/aws/alexa/httpserver/services/RequestEnvelopeService.java
  aws-alexa/src/main/java/io/micronaut/aws/alexa/builders/AlexaSkillBuilder.java
  aws-alexa/src/main/java/io/micronaut/aws/alexa/builders/DefaultAlexaSkillBuilder.java
  aws-alexa/src/main/java/io/micronaut/aws/alexa/builders/SkillBuilderProvider.java
  aws-alexa/src/main/java/io/micronaut/aws/alexa/builders/StandardSkillBuilderProvider.java
  aws-alexa/src/main/java/io/micronaut/aws/alexa/conf/AlexaSkillConfiguration.java
  aws-alexa/src/main/java/io/micronaut/aws/alexa/conf/AlexaSkillConfigurationProperties.java
  aws-alexa/src/main/java/io/micronaut/aws/alexa/flashbriefing/FlashBriefingItem.java
  aws-alexa/src/main/java/io/micronaut/aws/alexa/ssml/Ssml.java
  aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterQueryProvider.java
  aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterStoreConfigClient.java
  aws-parameter-store/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterStoreConfiguration.java
  aws-route53/src/main/java/io/micronaut/discovery/aws/route53/Route53ClientDiscoveryConfiguration.java
  function-aws-alexa/src/main/java/io/micronaut/function/aws/alexa/AlexaFunction.java
  function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/ContextProvider.java
  function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/DefaultServletToAwsProxyRequestAdapter.java
  function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/DefaultServletToAwsProxyResponseAdapter.java
  function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/MockContextProvider.java
  function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/ServletToAwsProxyRequestAdapter.java
  function-aws-api-proxy-test/src/main/java/io/micronaut/function/aws/proxy/test/ServletToAwsProxyResponseAdapter.java
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyRequest.java
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyResponse.java
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/BodySpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/FiltersSpec.groovy
  function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntime.java
  function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AwsLambdaRuntimeApi.java
  function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AwsLambdaRuntimeApiError.java
  function-aws-custom-runtime/src/test/java/io/micronaut/docs/Book.java
  function-aws-custom-runtime/src/test/java/io/micronaut/docs/BookSaved.java
  function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestHandler.java
  function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestStreamHandler.java
  function-aws/src/test/groovy/io/micronaut/function/aws/MappingDiagnosticContextSetterSpec.groovy
  function-client-aws/src/main/java/io/micronaut/function/client/aws/AWSLambdaConfiguration.java
Labels: type: improvement

#1052 build: add gradle scans
  settings.gradle
Labels: relates-to: build

#1053 awssdk bom from 2.16.52 to 2.16.59 aws-java-sdk-bom from 1.11.1009 to 1.11.1015
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
Labels: type: dependency-upgrade

#1058 build: don't specify micronaut-discovery-client version
  aws-parameter-store/build.gradle
Labels: relates-to: build

#1057 doc: split docs into sections
  src/main/docs/guide/sdkv2.adoc
  src/main/docs/guide/sdkv2/awsCredentials.adoc
  src/main/docs/guide/sdkv2/awsRegionSelection.adoc
  src/main/docs/guide/sdkv2/sdkHttpClient.adoc
  src/main/docs/guide/sdkv2/sdkHttpClient/apacheHttpClient.adoc
  src/main/docs/guide/sdkv2/sdkHttpClient/nettyClient.adoc
  src/main/docs/guide/sdkv2/sdkHttpClient/urlConnection.adoc
  src/main/docs/guide/thirdPartyLibraries.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#1061 build: gradle to 7.0.2
  .github/workflows/dependency-update.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#1067 graalvm 21.0.0.2 to 21.1.0.0
  .github/workflows/graalvm.yml
Labels: relates-to: build

#1070 docs: create distributed configuration section
  src/main/docs/guide/distributedconfiguration.adoc
  src/main/docs/guide/distributedconfiguration/parametersStore.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#1076 ci: set github branch from 2.5.x to 3.0.x
  gradle.properties
Labels: relates-to: build
