Repository micronaut-projects/micronaut-aws, pull requests merged in 2021-10, with the labels that each got.

#1190 ci: GRADLE_ENTERPRISE_ACCESS_KEY
  .github/workflows/gradle.yml
Labels: relates-to: build

#1188 Don't close application context between requests in MicronautRequestStreamHandler
  function-aws/build.gradle
  function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestStreamHandler.java
  function-aws/src/test/groovy/io/micronaut/function/aws/MicronautRequestStreamHandlerDontCloseCtxSpec.groovy
Labels: type: bug

#1192 Bump up micronaut three zero two
  gradle.properties
Labels: type: dependency-upgrade
