Repository micronaut-projects/micronaut-aws, pull requests merged in 2021-01, with the labels that each got.

#862 build: bump up micronaut-security to 2.2.1
  gradle.properties
Labels: relates-to: build

#861 build: bump up micronaut test to 2.3.1
  gradle.properties
Labels: relates-to: build

#863 test: bump up bcprov-jdk15on from 1.67 to 1.68
  aws-alexa-httpserver/build.gradle
Labels: relates-to: build

#865 build: pin jetty server to 9.4.35
  function-aws-api-proxy-test/build.gradle
Labels: type: dependency-upgrade

#748 Inject preconstructed ApplicationContext in Lambda handler
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaHandler.java
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/MicronautLambdaHandlerSpec.groovy
  function-aws-api-proxy/src/test/java/io/micronaut/function/aws/proxy/MicronautAwsProxyTest.java
  function-aws-test/build.gradle
  function-aws-test/src/main/java/io/micronaut/function/aws/test/MicronautLambdaJunit5Extension.java
  function-aws-test/src/main/java/io/micronaut/function/aws/test/annotation/MicronautLambdaTest.java
  function-aws-test/src/test/java/io/micronaut/function/aws/test/EagerSingleton.java
  function-aws-test/src/test/java/io/micronaut/function/aws/test/MicronautLambdaExtensionTest.java
  function-aws-test/src/test/resources/logback.xml
  function-aws/src/main/java/io/micronaut/function/aws/LambdaApplicationContextBuilder.java
  function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestHandler.java
  function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestStreamHandler.java
  gradle.properties
  settings.gradle
  src/main/docs/guide/lambda/lambdaTesting.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement

#866 Dependency upgrades
  aws-parameter-store/build.gradle
  aws-route53/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  function-client-aws/build.gradle
Labels: type: dependency-upgrade

#875 [aws] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build
