Repository micronaut-projects/micronaut-aws, pull requests merged in 2021-09, with the labels that each got.

#1158 build: bump up to Gradle 7.2
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#1165 fix: Move body decoding above arguments
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/BodyArgumentsSpec.groovy
Labels: type: bug

#1185 build: bump up to 3.0.2
  gradle.properties
  test-suite-kotlin/build.gradle
Labels: type: dependency-upgrade

#1182 ci: gradle enterprise keys to github actions
  .github/workflows/central-sync.yml
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
Labels: relates-to: build
