Repository micronaut-projects/micronaut-aws, pull requests merged in 2022-11, with the labels that each got.

#1472 ci: cli provenance
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#1500 build: use type safe project accessor
  aws-alexa-httpserver/build.gradle.kts
  aws-alexa/build.gradle.kts
  aws-cdk/build.gradle.kts
  aws-cloudwatch-logging/build.gradle.kts
  aws-common/build.gradle.kts
  aws-distributed-configuration/build.gradle.kts
  aws-parameter-store/build.gradle.kts
  aws-sdk-v1/build.gradle.kts
  aws-sdk-v2/build.gradle.kts
  aws-secretsmanager/build.gradle.kts
  aws-service-discovery/build.gradle.kts
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.aws-base.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.aws-module.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.aws-tests.gradle
  function-aws-alexa/build.gradle.kts
  function-aws-api-proxy-test/build.gradle.kts
  function-aws-api-proxy/build.gradle.kts
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyResponse.java
  function-aws-custom-runtime/build.gradle.kts
  function-aws-test/build.gradle.kts
  function-aws-test/src/main/java/io/micronaut/function/aws/test/annotation/MicronautLambdaTest.java
  function-aws/build.gradle.kts
  function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestHandler.java
  function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestStreamHandler.java
  function-aws/src/test/groovy/io/micronaut/function/aws/AfterExecutionEventSpec.groovy
  function-aws/src/test/groovy/io/micronaut/function/aws/MicronautStreamHandlerLambdaContextSpec.groovy
  function-client-aws/build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle.kts
  test-suite-aws-sdk-v2/build.gradle.kts
  test-suite-groovy/build.gradle.kts
  test-suite-kotlin/build.gradle.kts
  test-suite/build.gradle.kts
Labels: relates-to: build

#1511 graal: StsWebIdentityCredentialsProviderFactory class is loaded via reflection
  aws-sdk-v2/src/main/resources/META-INF/native-image/io.micronaut.aws/micronaut-aws-sdk-v2/reflect-config.json
Labels: relates-to: graal

#1510 build: removes dependency to Micronaut HTTP Netty
  function-aws-api-proxy/build.gradle.kts
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautResponseWriter.java
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/cookie/CookieEncoder.java
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/cookie/CookieHeaderNames.java
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/cookie/CookieUtil.java
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/cookie/DateFormatter.java
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/cookie/HttpConstants.java
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/cookie/ServerCookieEncoder.java
Labels: type: improvement

#1517 feat: Amazon API Gateway Stage resolution
  aws-apigateway/build.gradle.kts
  aws-apigateway/src/main/java/io/micronaut/aws/apigateway/APIGatewayProxyRequestEventStageResolver.java
  aws-apigateway/src/main/java/io/micronaut/aws/apigateway/AmazonApiGatewayUtils.java
  aws-apigateway/src/main/java/io/micronaut/aws/apigateway/HttpRequestStageResolver.java
  aws-apigateway/src/main/java/io/micronaut/aws/apigateway/StageResolver.java
  aws-apigateway/src/test/groovy/io/micronaut/aws/apigateway/APIGatewayProxyRequestEventStageResolverSpec.groovy
  aws-apigateway/src/test/groovy/io/micronaut/aws/apigateway/AmazonApiGatewayUtilsSpec.groovy
  aws-apigateway/src/test/groovy/io/micronaut/aws/apigateway/HttpRequestStageResolverSpec.groovy
  settings.gradle.kts
  src/main/docs/guide/amazonApiGateway.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement
