Repository micronaut-projects/micronaut-aws, pull requests merged in 2022-03, with the labels that each got.

#1243 build: bump software.amazon.awssdk:bom from 2.16.104 to 2.17.97
  aws-sdk-v2/src/main/java/io/micronaut/aws/sdk/v2/client/netty/NettyClientConfiguration.java
Labels: type: dependency-upgrade

#1296 Fix Kotlin code blocks for @FunctionClient
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/function/client/aws/atnamed/AnalyticsClient.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/function/client/aws/methodnamed/AnalyticsClient.kt
Labels: type: docs

#1272 build: sonarqube, GraalVM 22.0.0.2, Gradle 7.4 Junit5 for test-suite Java and Kotlin
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release-notes.yml
  .github/workflows/sonarqube.yml
  MAINTAINING.md
  SECURITY.md
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.aws-test-suite.gradle
  function-aws/build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  test-suite-groovy/build.gradle
  test-suite-kotlin/build.gradle
  test-suite-kotlin/src/test/groovy/io/micronaut/docs/function/client/aws/AnalyticsClientSpec.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/docs/function/aws/AnalyticsClientTest.kt
  test-suite/build.gradle
  test-suite/src/test/groovy/io/micronaut/docs/function/aws/AnalyticsClientSpec.groovy
  test-suite/src/test/groovy/io/micronaut/docs/function/aws/ContextFunctionNameSpec.groovy
  test-suite/src/test/groovy/io/micronaut/docs/function/aws/FactoryFunctionBeanSpec.groovy
  test-suite/src/test/groovy/io/micronaut/docs/function/aws/MicronautFunctionNameSpec.groovy
  test-suite/src/test/groovy/io/micronaut/docs/function/aws/MicronautRequestStreamHandlerOverrideResolveFunctionNameSpec.groovy
  test-suite/src/test/java/io/micronaut/docs/function/aws/AnalyticsClientTest.java
  test-suite/src/test/java/io/micronaut/docs/function/aws/ContextFunctionNameTest.java
  test-suite/src/test/java/io/micronaut/docs/function/aws/FactoryFunctionBeanTest.java
  test-suite/src/test/java/io/micronaut/docs/function/aws/MicronautFunctionNameTest.java
  test-suite/src/test/java/io/micronaut/docs/function/aws/MicronautRequestStreamHandlerOverrideResolveFunctionNameTest.java
Labels: relates-to: build

#1301 build: micronaut from 3.2.1 to 3.3.4
  gradle.properties
Labels: relates-to: build

#1303 ci: github action checkout to v3
  .github/workflows/central-sync.yml
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  config/checkstyle/checkstyle.xml
Labels: relates-to: build

#1309 build: update build plugin to 5.2.3
  settings.gradle
Labels: relates-to: build

#1312 ci: github actions sync
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#1322 Settings to 5.3.1 and update build
  aws-alexa-httpserver/build.gradle
  aws-alexa/build.gradle
  aws-common/build.gradle
  aws-distributed-configuration/build.gradle
  aws-parameter-store/build.gradle
  aws-sdk-v1/build.gradle
  aws-sdk-v2/build.gradle
  aws-secretsmanager/build.gradle
  aws-service-discovery/build.gradle
  function-aws-alexa/build.gradle
  function-aws-api-proxy-test/build.gradle
  function-aws-api-proxy/build.gradle
  function-aws-custom-runtime/build.gradle
  function-aws-test/build.gradle
  function-aws/build.gradle
  function-client-aws/build.gradle
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle
Labels: relates-to: build

#1324 build: remove spotbugs dependency
  aws-alexa-httpserver/build.gradle
  aws-alexa-httpserver/src/main/java/io/micronaut/aws/alexa/httpserver/conf/AlexaControllerConfiguration.java
  aws-alexa/build.gradle
  function-aws-alexa/build.gradle
  function-aws-custom-runtime/build.gradle
  gradle/libs.versions.toml
Labels: relates-to: build
