Repository micronaut-projects/micronaut-aws, pull requests merged in 2022-04, with the labels that each got.

#1310 Register Lambda Context as singletons and MDC for every Handler
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaHandler.java
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/LambdaContextSpec.groovy
  function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntime.java
  function-aws/src/main/java/io/micronaut/function/aws/DefaultDiagnosticInfoPopulator.java
  function-aws/src/main/java/io/micronaut/function/aws/DefaultLambdaContextFactory.java
  function-aws/src/main/java/io/micronaut/function/aws/DiagnosticInfoPopulator.java
  function-aws/src/main/java/io/micronaut/function/aws/HandlerUtils.java
  function-aws/src/main/java/io/micronaut/function/aws/LambdaContextFactory.java
  function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestHandler.java
  function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestStreamHandler.java
  function-aws/src/main/java/io/micronaut/function/aws/XRayUtils.java
  function-aws/src/test/groovy/io/micronaut/function/aws/LambdaContextSpec.groovy
  function-aws/src/test/groovy/io/micronaut/function/aws/MappingDiagnosticContextSetterSpec.groovy
  function-aws/src/test/groovy/io/micronaut/function/aws/MicronautRequestStreamHandlerSpec.groovy
  function-aws/src/test/groovy/io/micronaut/function/aws/MicronautStreamHandlerLambdaContextSpec.groovy
  function-aws/src/test/groovy/io/micronaut/function/aws/SquareHandler.groovy
  function-aws/src/test/groovy/io/micronaut/function/aws/SquareHandlerSpec.groovy
  src/main/docs/guide/lambda/lambdacontext.adoc
  src/main/docs/guide/toc.yml
Labels: type: bug

#1334 doc: Corretto with two r and two tt
  src/main/docs/guide/toc.yml
Labels: type: docs

#1327 build: micronaut 3.4.2
  .github/workflows/dependency-update.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#1346 ci: setup-java @v3
  .github/workflows/central-sync.yml
  .github/workflows/dependency-update.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
Labels: relates-to: build

#1313 build: update dependencies
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#1348 Dependency upgrades
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#1347 feat: adds AWS CDK module
  aws-cdk/build.gradle
  aws-cdk/src/main/java/io/micronaut/aws/cdk/function/MicronautFunction.java
  aws-cdk/src/main/java/io/micronaut/aws/cdk/function/MicronautFunctionFile.java
  aws-cdk/src/main/java/io/micronaut/aws/cdk/function/package-info.java
  aws-cdk/src/test/groovy/io/micronaut/aws/cdk/function/MicronautFunctionFileSpec.groovy
  aws-cdk/src/test/groovy/io/micronaut/aws/cdk/function/MicronautFunctionSpec.groovy
  aws-cdk/src/test/java/io/micronaut/docs/aws/cdk/function/AppStack.java
  aws-cdk/src/test/java/io/micronaut/docs/aws/cdk/function/MicronautFunctionFileExample.java
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle
  src/main/docs/guide/cdk.adoc
  src/main/docs/guide/cdk/micronautFunction.adoc
  src/main/docs/guide/cdk/micronautFunctionFile.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement

#1350 enable binary compatibility check for cdk
  aws-cdk/build.gradle
Labels: relates-to: build
