Repository micronaut-projects/micronaut-aws, pull requests merged in 2022-07, with the labels that each got.

#1403 ci: java 11 GraalVM matrix and Gradle 7.5
  .github/workflows/central-sync.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
Labels: relates-to: build

#1412 Duplicate decoding of query parameters arriving from Api Gateway proxy
  function-aws-api-proxy-test/src/test/groovy/io/micronaut/function/aws/proxy/test/AwsApiProxyTestServerSpec.groovy
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautAwsProxyRequest.java
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ParametersSpec.groovy
Labels: type: bug

#1413 @Factory classes from the Micronaut ApiGateway Websockets example
  aws-sdk-v2/build.gradle
  aws-sdk-v2/src/main/java/io/micronaut/aws/sdk/v2/service/gatewaymanagement/ApiGatewayManagementApiClientFactory.java
  aws-sdk-v2/src/main/java/io/micronaut/aws/sdk/v2/service/gatewaymanagement/package-info.java
  aws-sdk-v2/src/main/resources/META-INF/native-image/io.micronaut.aws/micronaut-aws-sdk-v2/native-image.properties
  aws-sdk-v2/src/test/groovy/io/micronaut/aws/sdk/v2/service/ApiGatewayManagementApiClientSpec.groovy
  gradle/libs.versions.toml
Labels: type: enhancement

#1414 fix: support binding Body form-url-encoded to POJO with lambda Apps
  function-aws-api-proxy/build.gradle
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/QueryStringDecoder.java
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/MicronautLambdaHandlerSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/QueryStringDecoderSpec.groovy
Labels: type: bug
