Repository micronaut-projects/micronaut-aws, pull requests merged in 2022-12, with the labels that each got.

#1524 ci: junit-report 3.6.1 slas3 1.4.0 Gradle 7.6
  config/checkstyle/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build

#1530 ci: only 17
  .github/workflows/central-sync.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
Labels: relates-to: build

#1549 fix: graal typehint for SingleValueHeaders
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
Labels: type: bug, relates-to: graal

#1551 build: dowgrade to 1.8.1 of aws-serverless-java-container
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautResponseWriter.java
  gradle/libs.versions.toml
Labels: type: dependency-upgrade, relates-to: graal

#1552 Add @Typehint for TreeMap as well
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautResponseWriter.java
  gradle/libs.versions.toml
Labels: relates-to: graal
