Repository micronaut-projects/micronaut-aws, pull requests merged in 2023-12, with the labels that each got.

#1963 bug: protect against null context
  aws-apigateway/src/main/java/io/micronaut/aws/apigateway/HttpRequestStageResolver.java
  aws-apigateway/src/test/groovy/io/micronaut/aws/apigateway/HttpRequestStageResolverSpec.groovy
  gradle/libs.versions.toml
Labels: type: improvement

#1968 [aws] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#1941 Fix S3 Event not deserialized properly
  aws-lambda-events-serde/src/main/java/io/micronaut/aws/lambda/events/serde/ResponseElementsEntitySerde.java
  aws-lambda-events-serde/src/main/java/io/micronaut/aws/lambda/events/serde/S3EventNotificationSerde.java
  aws-lambda-events-serde/src/main/java/io/micronaut/aws/lambda/events/serde/S3EventSerde.java
  aws-lambda-events-serde/src/main/java/io/micronaut/aws/lambda/events/serde/S3ObjectEntitySerde.java
  aws-lambda-events-serde/src/test/groovy/io/micronaut/aws/lambda/events/serde/S3EventNotificationSpec.groovy
  config/accepted-api-changes.json
Labels: type: bug

#1985 fix: start context in MicronautRequestStreamHandler
  function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestStreamHandler.java
  function-aws/src/test/groovy/io/micronaut/function/aws/ContextUtils.groovy
  function-aws/src/test/groovy/io/micronaut/function/aws/MicronautRequestStreamHandlerStartsContextSpec.groovy
Labels: type: bug
