Repository micronaut-projects/micronaut-aws, pull requests merged in 2023-10, with the labels that each got.

#1872 [aws] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#1912 docs: fix dependency for lambda handlers
  src/main/docs/guide/lambda/requestHandlers.adoc
Labels: type: docs

#1918 fix: don’t duplicate query values in getUri
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/ApiGatewayServletRequest.java
  test-suite-http-server-tck-function-aws-api-gateway-proxy-alb/src/test/java/io/micronaut/http/server/tck/lambda/tests/HttpRequestUriTest.java
  test-suite-http-server-tck-function-aws-api-gateway-proxy-payloadv1/src/test/java/io/micronaut/http/server/tck/lambda/tests/HttpRequestUriTest.java
  test-suite-http-server-tck-function-aws-api-gateway-proxy-payloadv2/src/test/java/io/micronaut/http/server/tck/lambda/tests/RequestUriTest.java
  test-suite-http-server-tck-function-aws-api-proxy-test/src/test/java/io/micronaut/http/server/tck/lambda/tests/HttpRequestUriTest.java
Labels: type: bug
