Repository micronaut-projects/micronaut-aws, pull requests merged in 2023-06, with the labels that each got.

#1744 ci: change renovate schedule
  .github/renovate.json
Labels: relates-to: build

#1745 fix: Micronaut Lambda Test compilation with 3.9.2
  aws-cloudwatch-logging/src/test/groovy/io/micronaut/aws/cloudwatch/logging/CloudwatchLoggingSpec.groovy
  function-aws-test/src/main/java/io/micronaut/function/aws/test/MicronautLambdaJunit5Extension.java
  function-aws-test/src/main/java/io/micronaut/function/aws/test/annotation/MicronautLambdaTest.java
  gradle/libs.versions.toml
  test-suite-http-server-tck-function-aws-api-proxy/src/test/java/io/micronaut/http/server/tck/lambda/tests/MicronautLambdaHandlerHttpServerTestSuite.java
Labels: type: bug, type: regression

#1753 [aws] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build

#1757 graal: more TypeHint.AccessTypes for Lambda Events
  function-aws-custom-runtime/build.gradle.kts
  function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntime.java
Labels: relates-to: graal

#1759 Added AWS S3 native tests
  aws-sdk-v2/src/main/resources/META-INF/native-image/io.micronaut.aws/micronaut-aws-sdk-v2/reflect-config.json
  buildSrc/src/main/groovy/io.micronaut.build.internal.aws-tests-resources.gradle
  gradle/libs.versions.toml
  settings.gradle.kts
  test-suite-s3/build.gradle.kts
  test-suite-s3/src/main/java/example/AbstractS3BucketController.java
  test-suite-s3/src/main/java/example/AsyncS3BucketController.java
  test-suite-s3/src/main/java/example/ListBucketsResult.java
  test-suite-s3/src/main/java/example/Result.java
  test-suite-s3/src/main/java/example/S3BucketController.java
  test-suite-s3/src/test/java/example/S3BucketTest.java
  test-suite-s3/src/test/resources/logback.xml
Labels: relates-to: graal

#1772 Workaround Core #9445
  function-aws/src/main/java/io/micronaut/function/aws/JsonMapperCustomPojoSerializer.java
Labels: type: bug

#1779 ci: checkout workflow 3.5.3
  .github/workflows/release.yml
Labels: relates-to: build
