Repository micronaut-projects/micronaut-aws, pull requests merged in 2023-01, with the labels that each got.

#1538 test: use HTTP Server TCK for function-aws-api-proxy
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.aws.http-server-tck-module.gradle
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/BodyArgumentsSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/BodySpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ConsumesSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/CookiesSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/DeleteWithoutBodySpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ErrorHandlerSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/FiltersSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/FluxSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/MicronautLambdaHandlerSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/MicronautLambdaHandlerStatusSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ObjectMapperListenerSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ObjectMapperSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ParametersSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/ResponseStatusSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/StatusSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/VersionSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/filters/FilterErrorSpec.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/filters/FilterException.java
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/filters/FilterExceptionException.java
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/filters/FilterExceptionExceptionHandler.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/filters/FilterExceptionHandler.groovy
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/filters/NextFilterException.java
  function-aws-api-proxy/src/test/groovy/io/micronaut/function/aws/proxy/filters/NextFilterExceptionHandler.groovy
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle.kts
  test-suite-http-server-tck-function-aws-api-proxy/build.gradle.kts
  test-suite-http-server-tck-function-aws-api-proxy/src/test/java/io/micronaut/http/server/tck/lambda/HttpHostResolverReplacement.java
  test-suite-http-server-tck-function-aws-api-proxy/src/test/java/io/micronaut/http/server/tck/lambda/LambdaServerUnderTest.java
  test-suite-http-server-tck-function-aws-api-proxy/src/test/java/io/micronaut/http/server/tck/lambda/LambdaServerUnderTestProvider.java
  test-suite-http-server-tck-function-aws-api-proxy/src/test/java/io/micronaut/http/server/tck/lambda/MultiValueHeadersAdapter.java
  test-suite-http-server-tck-function-aws-api-proxy/src/test/java/io/micronaut/http/server/tck/lambda/tests/MicronautLambdaHandlerHttpServerTestSuite.java
  test-suite-http-server-tck-function-aws-api-proxy/src/test/resources/META-INF/services/io.micronaut.http.server.tck.ServerUnderTestProvider
  test-suite-http-server-tck-function-aws-api-proxy/src/test/resources/logback.xml
  test-suite-kotlin/build.gradle.kts
Labels: relates-to: build

#1577 Support multiple prefixes for aws distributed configuration
  aws-distributed-configuration/src/main/java/io/micronaut/aws/distributedconfiguration/AwsDistributedConfiguration.java
  aws-distributed-configuration/src/main/java/io/micronaut/aws/distributedconfiguration/AwsDistributedConfigurationClient.java
  aws-distributed-configuration/src/main/java/io/micronaut/aws/distributedconfiguration/AwsDistributedConfigurationProperties.java
  aws-distributed-configuration/src/test/groovy/io/micronaut/aws/distributedconfiguration/AwsDistributedConfigurationSpec.groovy
Labels: type: improvement

#1582 build: projectAccessors and use version catalogue
  aws-cdk/build.gradle.kts
  function-aws-api-proxy-test/build.gradle.kts
  function-aws-custom-runtime/build.gradle.kts
  function-client-aws/build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  test-suite-aws-sdk-v2/build.gradle.kts
  test-suite-groovy/build.gradle.kts
  test-suite-kotlin/build.gradle.kts
  test-suite/build.gradle.kts
Labels: relates-to: build

#1532 ci: github actions sync
  .github/workflows/graalvm.yml
  config/checkstyle/checkstyle.xml
Labels: relates-to: build

#1591 Fix for drive-by localhost cors deny TCK test
  function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java
  gradle/libs.versions.toml
  test-suite-http-server-tck-function-aws-api-proxy/src/test/java/io/micronaut/http/server/tck/lambda/tests/MicronautLambdaHandlerHttpServerTestSuite.java
Labels: type: bug

#1593 ci: use 11
  .github/workflows/central-sync.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
Labels: relates-to: build
