Repository micronaut-projects/micronaut-aws, pull requests merged in 2023-07, with the labels that each got.

#1800 Graalvm metadata forv2 event
  function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntime.java
Labels: relates-to: graal

#1803 doc: Build Plugins mainClass Lambda Native
  src/main/docs/guide/lambda/customRuntimes.adoc
Labels: type: docs, relates-to: graal

#1819 gradle 8.2.1
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#1824 [aws] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
Labels: relates-to: build
