Repository micronaut-projects/micronaut-aws, pull requests merged in 2024-01, with the labels that each got.

#1997 fix: handle RequestStreamHandler in AbstractMicronautLambdaRuntime
  function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntime.java
  function-aws-custom-runtime/src/main/java/io/micronaut/function/aws/runtime/AbstractRequestStreamHandlerMicronautLambdaRuntime.java
  function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntimeSpec.groovy
  function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/micronautrequeststreamhandler/AbstractRequestStreamHandlerMicronautLambdaRuntimeSpec.groovy
  function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/micronautrequeststreamhandler/CustomRuntimeForMicronautRequestStreamHandlerSpec.groovy
  function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/micronautrequeststreamhandler/FunctionLambdaRuntime.groovy
  function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/micronautrequeststreamhandler/FunctionRequestHandler.groovy
  function-aws-custom-runtime/src/test/groovy/io/micronaut/function/aws/runtime/micronautrequeststreamhandler/RequestFunction.groovy
  function-aws-custom-runtime/src/test/resources/logback.xml
Labels: type: bug

#2001 doc: only abbreviated format is supported
  src/main/docs/guide/lambda/requestHandlers.adoc
Labels: type: docs

#2007 Add a test to verify MockBean works with MicronautLambdaTest
  function-aws-test/build.gradle.kts
  function-aws-test/src/test/java/io/micronaut/function/aws/test/MicronautLambdaExtensionMockBeanTest.java
  function-aws-test/src/test/resources/logback.xml
  gradle/libs.versions.toml
Labels: type: improvement

#2006 [aws] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#2026 [aws] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
Labels: relates-to: build
