Repository micronaut-projects/micronaut-aws, pull requests merged in 2024-02, with the labels that each got.

#2032 remove jackson-databind dep from secretsmanager
  aws-secretsmanager/build.gradle.kts
  aws-secretsmanager/src/main/java/io/micronaut/aws/secretsmanager/SecretsManagerGroupNameAwareKeyValueFetcher.java
  aws-secretsmanager/src/main/java/io/micronaut/aws/secretsmanager/SecretsManagerKeyValueFetcher.java
  config/accepted-api-changes.json
Labels: type: improvement

#2033 Document how to reduce the number of prefixes
  src/main/docs/guide/distributedconfiguration/distributedconfigurationsecretsmanagersearch.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#2034 doc: improve paramterstore configuration reference
  aws-distributed-configuration/src/main/java/io/micronaut/aws/distributedconfiguration/AwsDistributedConfigurationProperties.java
Labels: type: docs

#2035 Update dependencies
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#2038 testcontainers via test-resources version catalog
  buildSrc/src/main/groovy/io.micronaut.build.internal.aws-tests-resources.gradle
  function-aws/build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: relates-to: build

#2042 assertj via micronaut-test version catalog
  aws-lambda-events-serde/build.gradle.kts
  gradle/libs.versions.toml
Labels: relates-to: build

#2044 [aws] Update common files for branch master
  .github/workflows/graalvm-dev.yml
Labels: relates-to: build

#2064 [aws] Update common files for branch master
  .github/workflows/gradle.yml
  gradlew.bat
Labels: relates-to: build
